name: ${COMPOSE_PROJECT_NAME}

services:
  nos3-fortytwo:
    image: ghcr.io/haisamido/nos3-base-fortytwo:dev
    env_file:
      - ./.env
    build:
      context: ./services/fortytwo
      dockerfile: Dockerfile
      args:
        DEPLOYMENT_ENVIRO: ${DEPLOYMENT_ENVIRO}
        HTTPS_PROXY: ${HTTPS_PROXY}
        HTTP_PROXY: ${HTTP_PROXY}
        NO_PROXY: ${NO_PROXY}
        MAVEN_HTTPS_PROXY: ${MAVEN_HTTPS_PROXY}
        GIT_URL: ${FORTYTWO_GIT_URL}
        GIT_COMMIT: ${FORTYTWO_GIT_COMMIT}
        GIT_FOLDER: ${FORTYTWO_GIT_FOLDER:-42}
        STARTUP_FOLDER: ${FORTYTWO_STARTUP_FOLDER}
        RECOMPILE: ${FORTYTWO_RECOMPILE:-false}
        BASE_DIR: ${FORTYTWO_BASE_DIR}
        VNC_PASSWORD: ${FORTYTWO_VNC_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "/usr/bin/pgrep -f 42 | grep -v xterm ; sleep 2"]
      interval: 10s
      timeout: 5s
      retries: 7
    attach: true
    container_name: ${COMPOSE_PROJECT_NAME}-fortytwo
    hostname: ${COMPOSE_PROJECT_NAME}-fortytwo
    working_dir: "/opt/nasa-itc/"
    command: '/entrypoint.sh'
    volumes:
      - ${PWD}/${NOS3_CFG_PATH}/cfg/build/InOut/:/opt/nasa-itc/42/NOS3InOut/
      - ${PWD}/${NOS3_CFG_PATH}/cfg/build/InOut/Inp_IPC.txt:/opt/nasa-itc/42/NOS3InOut/Inp_IPC.txt
      - ${PWD}/${NOS3_CFG_PATH}/cfg/build/InOut/Inp_Sim.txt:/opt/nasa-itc/42/NOS3InOut/Inp_Sim.txt
      - ${PWD}/services/fortytwo/entrypoint.sh:/entrypoint.sh
    ports:
      - "127.0.0.1:${FORTYTWO_PORT}:80"
    environment:
      DEPLOYMENT_ENVIRO: ${DEPLOYMENT_ENVIRO}
      HTTPS_PROXY: ${HTTPS_PROXY}
      HTTP_PROXY: ${HTTP_PROXY}
      NO_PROXY: ${NO_PROXY}
      MAVEN_HTTPS_PROXY: ${MAVEN_HTTPS_PROXY}
      GIT_URL: ${FORTYTWO_GIT_URL}
      GIT_COMMIT: ${FORTYTWO_GIT_COMMIT}
      GIT_FOLDER: ${FORTYTWO_GIT_FOLDER:-42}
      STARTUP_FOLDER: ${FORTYTWO_STARTUP_FOLDER}
      RECOMPILE: ${FORTYTWO_RECOMPILE:-false}
      BASE_DIR: ${FORTYTWO_BASE_DIR}
      VNC_PASSWORD: ${FORTYTWO_VNC_PASSWORD}
      MISSION: ${MISSION}
      SPACECRAFT: ${SPACECRAFT}
      PROJECT_NAME: ${PROJECT_NAME}
      HOST_PORT: ${FORTYTWO_PORT}
    networks:
      nos3-m01-sc01-00:
        aliases:
          - fortytwo
      nos3-m01-core-00:

  nos3-gsw:
    image: ghcr.io/haisamido/nos3-base-yamcs:dev
    env_file:
      - ./.env
    build:
      context: ./services/yamcs
      dockerfile: Dockerfile
      args:
        DEPLOYMENT_ENVIRO: ${DEPLOYMENT_ENVIRO}
        HEALTHCHECK_PORT: ${HEALTHCHECK_PORT}
        HTTPS_PROXY: ${HTTPS_PROXY}
        HTTP_PROXY: ${HTTP_PROXY}
        NO_PROXY: ${NO_PROXY}
        MAVEN_REPO_LOCAL: ${MAVEN_REPO_LOCAL}
        MAVEN_HTTPS_PROXY: ${MAVEN_HTTPS_PROXY}
        COMPONENT_DIR: ${COMPONENT_DIR}
        YAMCS_DATA_DIR: ${YAMCS_DATA_DIR}
        GSW_SOFTWARE: ${GSW_SOFTWARE}
        GIT_URL: ${YAMCS_GIT_URL}
        GIT_COMMIT: ${YAMCS_GIT_COMMIT}
    healthcheck:
      test: ["CMD-SHELL", "curl http://localhost:8090/api"]
      interval: 10s
      timeout: 5s
      retries: 10
    attach: true
    container_name: ${COMPOSE_PROJECT_NAME}-gsw
    hostname: ${COMPOSE_PROJECT_NAME}-gsw
    working_dir: "/home/nos3/.nos3/yamcs"
    command: "/entrypoint.sh"
    volumes:
      - ${PWD}/services/yamcs/entrypoint.sh:/entrypoint.sh
      - ${PWD}/services/yamcs/settings.xml:/home/nos3/.nos3/yamcs/settings.xml
    ports:
      - "127.0.0.1:${YAMCS_HOST_PORT}:${YAMCS_PORT}"
    tty: true
    stdin_open: true
    privileged: true
    environment:
      DEPLOYMENT_ENVIRO: ${DEPLOYMENT_ENVIRO}
      HEALTHCHECK_PORT: ${HEALTHCHECK_PORT}
      HTTPS_PROXY: ${HTTPS_PROXY}
      HTTP_PROXY: ${HTTP_PROXY}
      NO_PROXY: ${NO_PROXY}
      MAVEN_REPO_LOCAL: ${MAVEN_REPO_LOCAL}
      MAVEN_HTTPS_PROXY: ${MAVEN_HTTPS_PROXY}
      COMPONENT_DIR: ${COMPONENT_DIR}
      YAMCS_DATA_DIR: ${YAMCS_DATA_DIR}
      GSW_SOFTWARE: ${GSW_SOFTWARE}
      GIT_URL: ${YAMCS_GIT_URL}
      GIT_COMMIT: ${YAMCS_GIT_COMMIT}
      MISSION: ${MISSION}
      SPACECRAFT: ${SPACECRAFT}
      PROJECT_NAME: ${PROJECT_NAME}
    networks:
      nos3-m01-sc01-00:
        aliases:
          - active-gs
          - yamcs
          - cosmos
      nos3-m01-core-00:

  nos3-onair:
    image: nos3-base-local:dev
    env_file:
      - ./.env
    attach: true
    container_name: ${COMPOSE_PROJECT_NAME}-onair
    hostname: ${COMPOSE_PROJECT_NAME}-onair
    working_dir: /home/nos3/builds/nos3/fsw/build/exe/cpu1
    command: "/home/nos3/builds/nos3/scripts/fsw/onair_launch.sh"
    volumes:
      - ${PWD}/${NOS3_CFG_PATH}/cfg/build/sims/nos3-simulator.xml:/home/nos3/builds/nos3/sims/build/bin/nos3-simulator.xml
    tty: true
    stdin_open: true
    privileged: true
    environment:
      BASE_DIR: /home/nos3/builds/nos3
      FSW_DIR: /home/nos3/builds/nos3/fsw/build/exe/cpu1
      HEALTHCHECK_PORT: ${HEALTHCHECK_PORT}
      SCRIPT_DIR:
      MISSION: ${MISSION}
      SPACECRAFT: ${SPACECRAFT}
      PROJECT_NAME: ${PROJECT_NAME}
    networks:
      nos3-m01-sc01-00:
        aliases:
          - onair
          - sc01-onair
      nos3-m01-core-00:

  nos3-fsw:
    image: nos3-base-local:dev
    env_file:
      - ./.env
    build:
      context: ./services/fsw
      dockerfile: Dockerfile
      args:

        DEPLOYMENT_ENVIRO: ${DEPLOYMENT_ENVIRO}
        HTTPS_PROXY: ${HTTPS_PROXY}
        HTTP_PROXY: ${HTTP_PROXY}
        NO_PROXY: ${NO_PROXY}
        MAVEN_HTTPS_PROXY: ${MAVEN_HTTPS_PROXY}

        GIT_URL: ${NOS3_GIT_URL}
        GIT_COMMIT: ${NOS3_GIT_COMMIT}
        
        NOS3_USER: ${NOS3_USER}
        BASE_DIR: ${NOS3_BASE_DIR}
        IMAGE_URI: ${NOS3_IMAGE_URI}
        FSW_SOFTWARE: ${FSW_SOFTWARE}
        GSW_SOFTWARE: ${GSW_SOFTWARE}
        LD_LIBRARY_PATH: /usr/local/lib
        GROUND_SOFTWARE: ${GSW_SOFTWARE}

    healthcheck:
      test: ["CMD-SHELL", "/usr/bin/pgrep core-cpu1"]
      interval: 10s
      timeout: 5s
      retries: 5
    attach: true
    depends_on:
      nos3-fortytwo:
        condition: service_healthy
      nos3-nos-engine-server:
        condition: service_healthy
    container_name: ${COMPOSE_PROJECT_NAME}-fsw
    hostname: ${COMPOSE_PROJECT_NAME}-fsw
    working_dir: /home/nos3/builds/nos3/
    volumes:
      - ${PWD}/services/fsw/entrypoint.sh:/entrypoint.sh
    command: "/entrypoint.sh"
    sysctls:
      fs.mqueue.msg_max: 10000
    ulimits:
      rtprio: 99
    cap_add:
      - sys_nice
    environment:
      BASE_DIR: /home/nos3/builds/nos3
      FSW_DIR: /home/nos3/builds/nos3/fsw/build/exe/cpu1
      HEALTHCHECK_PORT: ${HEALTHCHECK_PORT}
      MISSION: ${MISSION}
      SPACECRAFT: ${SPACECRAFT}
      PROJECT_NAME: ${PROJECT_NAME}
    networks:
      nos3-m01-sc01-00:
        aliases:
          - fsw
          - sc01-fsw
      nos3-m01-core-00:

  nos3-nos-engine-server:
    image: nos3-base-local:dev
    env_file:
      - ./.env
    attach: true
    depends_on:
      nos3-fortytwo:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "/usr/bin/nc -vz nos-engine-server 12000 && /usr/bin/nc -vz nos-engine-server 12001"]
      interval: 10s
      timeout: 5s
      retries: 5
    container_name: ${COMPOSE_PROJECT_NAME}-nos-engine-server
    hostname: ${COMPOSE_PROJECT_NAME}-nos-engine-server
    working_dir: /home/nos3/builds/nos3/sims/build/bin
    command: "/usr/bin/nos_engine_server_standalone -f ./nos_engine_server_config.json"
    volumes:
      - ${PWD}/${NOS3_CFG_PATH}/cfg/build/sims/nos_engine_server_config.json:/home/nos3/builds/nos3/sims/build/bin/nos_engine_server_config.json
    ports:
      - "127.0.0.1:12000:12000"
      - "127.0.0.1:12001:12001"
    tty: true
    environment:
      HEALTHCHECK_PORT: ${HEALTHCHECK_PORT}
      MISSION: ${MISSION}
      SPACECRAFT: ${SPACECRAFT}
      PROJECT_NAME: ${PROJECT_NAME}
    networks:
      nos3-m01-sc01-00:
        aliases:
# TODO: below is needed for some reason!
          - sc01-nos-engine-server
          - nos-engine-server
      nos3-m01-core-00:

  nos3-truth42sim:
    image: nos3-base-local:dev
    env_file:
      - ./.env
    attach: true
    depends_on:
      nos3-fortytwo:
        condition: service_healthy
      nos3-gsw:
        condition: service_healthy
      nos3-nos-engine-server:
        condition: service_healthy        
    container_name: ${COMPOSE_PROJECT_NAME}-truth42sim
    hostname: ${COMPOSE_PROJECT_NAME}-truth42sim
    working_dir: /home/nos3/builds/nos3/sims/build/bin
    command: "./nos3-single-simulator -f ./nos3-simulator.xml truth42sim"
    volumes:
      - ${PWD}/${NOS3_CFG_PATH}/cfg/build/sims/nos3-simulator.xml:/home/nos3/builds/nos3/sims/build/bin/nos3-simulator.xml
    tty: true
    stdin_open: true
    privileged: true
    environment:
      HEALTHCHECK_PORT: ${HEALTHCHECK_PORT}
      MISSION: ${MISSION}
      SPACECRAFT: ${SPACECRAFT}
      PROJECT_NAME: ${PROJECT_NAME}
    networks:
      nos3-m01-sc01-00:
        aliases:
          - truth42sim
      nos3-m01-core-00:

  nos3-nos-terminal:
    image: nos3-base-local:dev
    env_file:
      - ./.env
    attach: true
    container_name: ${COMPOSE_PROJECT_NAME}-nos-terminal
    hostname: ${COMPOSE_PROJECT_NAME}-nos-terminal
    working_dir: /home/nos3/builds/nos3/sims/build/bin
    command: "./nos3-single-simulator -f ./nos3-simulator.xml stdio-terminal"
    volumes:
      - ${PWD}/${NOS3_CFG_PATH}/cfg/build/sims/nos3-simulator.xml:/home/nos3/builds/nos3/sims/build/bin/nos3-simulator.xml
    tty: true
    stdin_open: true
    privileged: true
    environment:
      HEALTHCHECK_PORT: ${HEALTHCHECK_PORT}
      MISSION: ${MISSION}
      SPACECRAFT: ${SPACECRAFT}
      PROJECT_NAME: ${PROJECT_NAME}
    networks:
      nos3-m01-sc01-00:
        aliases:
          - nos-terminal
      nos3-m01-core-00:

  nos3-nos-udp-terminal:
    image: nos3-base-local:dev
    env_file:
      - ./.env
    attach: true
    container_name: ${COMPOSE_PROJECT_NAME}-nos-udp-terminal
    hostname: ${COMPOSE_PROJECT_NAME}-nos-udp-terminal
    working_dir: /home/nos3/builds/nos3/sims/build/bin
    command: "./nos3-single-simulator -f ./nos3-simulator.xml udp-terminal"
    volumes:
      - ${PWD}/${NOS3_CFG_PATH}/cfg/build/sims/nos3-simulator.xml:/home/nos3/builds/nos3/sims/build/bin/nos3-simulator.xml
    tty: true
    stdin_open: true
    privileged: true
    environment:
      HEALTHCHECK_PORT: ${HEALTHCHECK_PORT}
      MISSION: ${MISSION}
      SPACECRAFT: ${SPACECRAFT}
      PROJECT_NAME: ${PROJECT_NAME}
    networks:
      nos3-m01-sc01-00:
        aliases:
          - nos-udp-terminal
      nos3-m01-core-00:

  nos3-nos-sim-bridge:
    image: nos3-base-local:dev
    env_file:
      - ./.env
    attach: true
    container_name: nos-sim-bridge
    working_dir: /home/nos3/builds/nos3/sims/build/bin
    command: "./nos3-sim-cmdbus-bridge -f ./nos3-simulator.xml"
    volumes:
      - ${PWD}/${NOS3_CFG_PATH}/cfg/build/sims/nos3-simulator.xml:/home/nos3/builds/nos3/sims/build/bin/nos3-simulator.xml
    tty: true
    stdin_open: true
    privileged: true
    environment:
      HEALTHCHECK_PORT: ${HEALTHCHECK_PORT}
      MISSION: ${MISSION}
      SPACECRAFT: ${SPACECRAFT}
      PROJECT_NAME: ${PROJECT_NAME}
    networks:
      nos3-m01-sc01-00:
      nos3-m01-core-00:

  nos3-camsim:
    image: nos3-base-local:dev
    env_file:
      - ./.env
    attach: true
    depends_on:
      nos3-fortytwo:
        condition: service_healthy
      nos3-fsw:
        condition: service_healthy
    container_name: sc01-cam-sim
    working_dir: /home/nos3/builds/nos3/sims/build/bin
    command: "./nos3-single-simulator -f ./nos3-simulator.xml camsim"
    volumes:
      - ${PWD}/${NOS3_CFG_PATH}/cfg/build/sims/nos3-simulator.xml:/home/nos3/builds/nos3/sims/build/bin/nos3-simulator.xml
    environment:
      HEALTHCHECK_PORT: ${HEALTHCHECK_PORT}
      MISSION: ${MISSION}
      SPACECRAFT: ${SPACECRAFT}
      PROJECT_NAME: ${PROJECT_NAME}
    networks:
      nos3-m01-sc01-00:
        aliases:
          - camsim
          - sc01-camsim
      nos3-m01-core-00:

  nos3-css-sim:
    image: nos3-base-local:dev
    env_file:
      - ./.env
    attach: true
    depends_on:
      nos3-fortytwo:
        condition: service_healthy
      nos3-fsw:
        condition: service_healthy
    container_name: sc01-css-sim
    working_dir: /home/nos3/builds/nos3/sims/build/bin
    command: "./nos3-single-simulator -f ./nos3-simulator.xml generic-css-sim"
    volumes:
      - ${PWD}/${NOS3_CFG_PATH}/cfg/build/sims/nos3-simulator.xml:/home/nos3/builds/nos3/sims/build/bin/nos3-simulator.xml
    environment:
      HEALTHCHECK_PORT: ${HEALTHCHECK_PORT}
      MISSION: ${MISSION}
      SPACECRAFT: ${SPACECRAFT}
      PROJECT_NAME: ${PROJECT_NAME}
    networks:
      nos3-m01-sc01-00:
        aliases:
          - css
      nos3-m01-core-00:

  nos3-eps-sim:
    image: nos3-base-local:dev
    env_file:
      - ./.env
    attach: true
    depends_on:
      nos3-nos-engine-server:
        condition: service_healthy
      nos3-fortytwo:
        condition: service_healthy
      nos3-fsw:
        condition: service_healthy
    container_name: sc01-eps-sim
    working_dir: /home/nos3/builds/nos3/sims/build/bin
    command: "./nos3-single-simulator -f ./nos3-simulator.xml generic-eps-sim"
    volumes:
      - ${PWD}/${NOS3_CFG_PATH}/cfg/build/sims/nos3-simulator.xml:/home/nos3/builds/nos3/sims/build/bin/nos3-simulator.xml
    environment:
      HEALTHCHECK_PORT: ${HEALTHCHECK_PORT}
      MISSION: ${MISSION}
      SPACECRAFT: ${SPACECRAFT}
      PROJECT_NAME: ${PROJECT_NAME}
    networks:
      nos3-m01-sc01-00:
        aliases:
          - eps
      nos3-m01-core-00:

  nos3-fss-sim:
    image: nos3-base-local:dev
    env_file:
      - ./.env
    attach: true
    depends_on:
      nos3-fortytwo:
        condition: service_healthy
      nos3-fsw:
        condition: service_healthy
    container_name: sc01-fss-sim
    working_dir: /home/nos3/builds/nos3/sims/build/bin
    command: "./nos3-single-simulator -f ./nos3-simulator.xml generic-fss-sim"
    volumes:
      - ${PWD}/${NOS3_CFG_PATH}/cfg/build/sims/nos3-simulator.xml:/home/nos3/builds/nos3/sims/build/bin/nos3-simulator.xml
    environment:
      HEALTHCHECK_PORT: ${HEALTHCHECK_PORT}
      MISSION: ${MISSION}
      SPACECRAFT: ${SPACECRAFT}
      PROJECT_NAME: ${PROJECT_NAME}
    networks:
      nos3-m01-sc01-00:
        aliases:
          - fss
      nos3-m01-core-00:

  nos3-gps-sim:
    image: nos3-base-local:dev
    env_file:
      - ./.env
    attach: true
    depends_on:
      nos3-fortytwo:
        condition: service_healthy
      nos3-fsw:
        condition: service_healthy
    container_name: sc01-gps-sim
    working_dir: /home/nos3/builds/nos3/sims/build/bin
    command: "./nos3-single-simulator -f ./nos3-simulator.xml gps"
    volumes:
      - ${PWD}/${NOS3_CFG_PATH}/cfg/build/sims/nos3-simulator.xml:/home/nos3/builds/nos3/sims/build/bin/nos3-simulator.xml
    environment:
      HEALTHCHECK_PORT: ${HEALTHCHECK_PORT}
      MISSION: ${MISSION}
      SPACECRAFT: ${SPACECRAFT}
      PROJECT_NAME: ${PROJECT_NAME}
    networks:
      nos3-m01-sc01-00:
        aliases:
          - gps
      nos3-m01-core-00:

  nos3-imu-sim:
    image: nos3-base-local:dev
    env_file:
      - ./.env
    attach: true
    depends_on:
      nos3-fortytwo:
        condition: service_healthy
      nos3-fsw:
        condition: service_healthy
    container_name: sc01-imu-sim
    working_dir: /home/nos3/builds/nos3/sims/build/bin
    command: "./nos3-single-simulator -f ./nos3-simulator.xml generic-imu-sim"
    volumes:
      - ${PWD}/${NOS3_CFG_PATH}/cfg/build/sims/nos3-simulator.xml:/home/nos3/builds/nos3/sims/build/bin/nos3-simulator.xml
    environment:
      HEALTHCHECK_PORT: ${HEALTHCHECK_PORT}
      MISSION: ${MISSION}
      SPACECRAFT: ${SPACECRAFT}
      PROJECT_NAME: ${PROJECT_NAME}
    networks:
      nos3-m01-sc01-00:
        aliases:
          - imu
      nos3-m01-core-00:

  nos3-mag-sim:
    image: nos3-base-local:dev
    env_file:
      - ./.env
    attach: true
    depends_on:
      nos3-fortytwo:
        condition: service_healthy
      nos3-fsw:
        condition: service_healthy
    container_name: sc01-mag-sim
    working_dir: /home/nos3/builds/nos3/sims/build/bin
    command: "./nos3-single-simulator -f ./nos3-simulator.xml generic-mag-sim"
    volumes:
      - ${PWD}/${NOS3_CFG_PATH}/cfg/build/sims/nos3-simulator.xml:/home/nos3/builds/nos3/sims/build/bin/nos3-simulator.xml
    environment:
      HEALTHCHECK_PORT: ${HEALTHCHECK_PORT}
      MISSION: ${MISSION}
      SPACECRAFT: ${SPACECRAFT}
      PROJECT_NAME: ${PROJECT_NAME}
    networks:
      nos3-m01-sc01-00:
        aliases:
          - mag
      nos3-m01-core-00:

  nos3-rw-sim0:
    image: nos3-base-local:dev
    env_file:
      - ./.env
    attach: true
    depends_on:
      nos3-fortytwo:
        condition: service_healthy
      nos3-fsw:
        condition: service_healthy
    container_name: sc01-rw-sim0
    working_dir: /home/nos3/builds/nos3/sims/build/bin
    command: "./nos3-single-simulator -f ./nos3-simulator.xml generic-reactionwheel-sim0"
    volumes:
      - ${PWD}/${NOS3_CFG_PATH}/cfg/build/sims/nos3-simulator.xml:/home/nos3/builds/nos3/sims/build/bin/nos3-simulator.xml
    environment:
      HEALTHCHECK_PORT: ${HEALTHCHECK_PORT}
      MISSION: ${MISSION}
      SPACECRAFT: ${SPACECRAFT}
      PROJECT_NAME: ${PROJECT_NAME}
    networks:
      nos3-m01-sc01-00:
        aliases:
          - rw0
      nos3-m01-core-00:

  nos3-rw-sim1:
    image: nos3-base-local:dev
    env_file:
      - ./.env
    attach: true
    depends_on:
      nos3-fortytwo:
        condition: service_healthy
      nos3-fsw:
        condition: service_healthy
    container_name: sc01-rw-sim1
    working_dir: /home/nos3/builds/nos3/sims/build/bin
    command: "./nos3-single-simulator -f ./nos3-simulator.xml generic-reactionwheel-sim1"
    volumes:
      - ${PWD}/${NOS3_CFG_PATH}/cfg/build/sims/nos3-simulator.xml:/home/nos3/builds/nos3/sims/build/bin/nos3-simulator.xml
    environment:
      HEALTHCHECK_PORT: ${HEALTHCHECK_PORT}
      MISSION: ${MISSION}
      SPACECRAFT: ${SPACECRAFT}
      PROJECT_NAME: ${PROJECT_NAME}
    networks:
      nos3-m01-sc01-00:
        aliases:
          - rw1
      nos3-m01-core-00:

  nos3-rw-sim2:
    image: nos3-base-local:dev
    env_file:
      - ./.env
    attach: true
    depends_on:
      nos3-fortytwo:
        condition: service_healthy
      nos3-fsw:
        condition: service_healthy
    container_name: sc01-rw-sim2
    working_dir: /home/nos3/builds/nos3/sims/build/bin
    command: "./nos3-single-simulator -f ./nos3-simulator.xml generic-reactionwheel-sim2"
    volumes:
      - ${PWD}/${NOS3_CFG_PATH}/cfg/build/sims/nos3-simulator.xml:/home/nos3/builds/nos3/sims/build/bin/nos3-simulator.xml
    environment:
      HEALTHCHECK_PORT: ${HEALTHCHECK_PORT}
      MISSION: ${MISSION}
      SPACECRAFT: ${SPACECRAFT}
      PROJECT_NAME: ${PROJECT_NAME}
    networks:
      nos3-m01-sc01-00:
        aliases:
          - rw2
      nos3-m01-core-00:

  # nos3-radio-sim:
  #   image: ghcr.io/haisamido/nos3-base:dev
  #   env_file:
  #     - ./.env
  #   attach: true
  #   healthcheck:
  #     test: [ "CMD-SHELL", "/usr/bin/pgrep -f nos3-single-simulator" ]
  #     interval: 10s
  #     timeout: 5s
  #     retries: 7
  #   depends_on:
  #     nos3-cryptolib:
  #       condition: service_started
  #   container_name: sc01-radio-sim
  #   hostname: radio-sim
  #   working_dir: /home/nos3/builds/nos3/sims/build/bin
  #   command: "/entrypoint.sh"
  #   volumes:
  #     - ${PWD}/${NOS3_CFG_PATH}/cfg/build/sims/nos3-simulator.xml:/home/nos3/builds/nos3/sims/build/bin/nos3-simulator.xml
  #     - ${PWD}/radio-sim/entrypoint.sh:/entrypoint.sh
  #   environment:
  #     HEALTHCHECK_PORT: ${HEALTHCHECK_PORT}
  #   networks:
  #     nos3-m01-sc01-00:
  #       # aliases:
  #       #   - radio-sim
  #     nos3-m01-core-00:

#   nos3-cryptolib:
#     image: nos3-base-local:dev
#     env_file:
#       - ./.env
#     attach: true
#     healthcheck:
#       test: ["CMD-SHELL", "/usr/bin/pgrep -f ./support/standalone"]
#       interval: 10s
#       timeout: 5s
#       retries: 5
#     depends_on:
#       # nos3-radio-sim:
#       #   condition: service_started
#       nos3-fsw:
#         condition: service_healthy
#     container_name: sc01_cryptolib-gsw
# #    hostname: cryptolib
#     working_dir: /home/nos3/builds/nos3/gsw/build
#     command: "./support/standalone"
#     volumes:
#       - ${PWD}/${NOS3_CFG_PATH}/cfg/build/sims/nos3-simulator.xml:/home/nos3/builds/nos3/sims/build/bin/nos3-simulator.xml
#     environment:
#       HEALTHCHECK_PORT: ${HEALTHCHECK_PORT}
#     networks:
#       nos3-m01-sc01-00:
#         aliases:
#           - cryptolib
#       nos3-m01-core-00:

  nos3-radio-sim-cryptolib:
    image: nos3-base-local:dev
    env_file:
      - ./.env
    attach: true
    healthcheck:
      test: [ "CMD-SHELL", "/usr/bin/pgrep -f nos3-single-simulator && /usr/bin/pgrep -f ./support/standalone" ]
      interval: 10s
      timeout: 5s
      retries: 7
    depends_on:
      nos3-fsw:
        condition: service_healthy
      nos3-gsw:
        condition: service_healthy
    container_name: sc01-radio-sim-cryptolib
    hostname: radio-sim-cryptolib
    working_dir: /home/nos3/builds/nos3/sims/build/bin
    command: "/entrypoint.sh"
    volumes:
      - ${PWD}/${NOS3_CFG_PATH}/cfg/build/sims/nos3-simulator.xml:/home/nos3/builds/nos3/sims/build/bin/nos3-simulator.xml
      - ${PWD}/services/radio-sim/entrypoint2.sh:/entrypoint.sh
    environment:
      HEALTHCHECK_PORT: ${HEALTHCHECK_PORT}
      MISSION: ${MISSION}
      SPACECRAFT: ${SPACECRAFT}
      PROJECT_NAME: ${PROJECT_NAME}
    networks:
      nos3-m01-sc01-00:
        aliases:
          - radio-sim
          - cryptolib
      nos3-m01-core-00:

  nos3-sample-sim:
    image: nos3-base-local:dev
    env_file:
      - ./.env
    attach: true
    depends_on:
      nos3-fortytwo:
        condition: service_healthy
      nos3-fsw:
        condition: service_healthy
    container_name: sc01-sample-sim
    working_dir: /home/nos3/builds/nos3/sims/build/bin
    command: "./nos3-single-simulator -f ./nos3-simulator.xml sample-sim"
    volumes:
      - ${PWD}/${NOS3_CFG_PATH}/cfg/build/sims/nos3-simulator.xml:/home/nos3/builds/nos3/sims/build/bin/nos3-simulator.xml
    environment:
      HEALTHCHECK_PORT: ${HEALTHCHECK_PORT}
      MISSION: ${MISSION}
      SPACECRAFT: ${SPACECRAFT}
      PROJECT_NAME: ${PROJECT_NAME}
    networks:
      nos3-m01-sc01-00:
      nos3-m01-core-00:

  nos3-startrk-sim:
    image: nos3-base-local:dev
    env_file:
      - ./.env
    attach: true
    depends_on:
      nos3-fortytwo:
        condition: service_healthy
      nos3-fsw:
        condition: service_healthy
    container_name: sc01-startrk-sim
    working_dir: /home/nos3/builds/nos3/sims/build/bin
    command: "./nos3-single-simulator -f ./nos3-simulator.xml generic-star-tracker-sim"
    volumes:
      - ${PWD}/${NOS3_CFG_PATH}/cfg/build/sims/nos3-simulator.xml:/home/nos3/builds/nos3/sims/build/bin/nos3-simulator.xml
    environment:
      HEALTHCHECK_PORT: ${HEALTHCHECK_PORT}
      MISSION: ${MISSION}
      SPACECRAFT: ${SPACECRAFT}
      PROJECT_NAME: ${PROJECT_NAME}
    networks:
      nos3-m01-sc01-00:
      nos3-m01-core-00:

  nos3-thruster-sim:
    image: nos3-base-local:dev
    env_file:
      - ./.env
    attach: true
    depends_on:
      nos3-fortytwo:
        condition: service_healthy
      nos3-fsw:
        condition: service_healthy
    container_name: sc01-thruster-sim
    working_dir: /home/nos3/builds/nos3/sims/build/bin
    command: "./nos3-single-simulator -f ./nos3-simulator.xml generic-thruster-sim"
    volumes:
      - ${PWD}/${NOS3_CFG_PATH}/cfg/build/sims/nos3-simulator.xml:/home/nos3/builds/nos3/sims/build/bin/nos3-simulator.xml
    environment:
      HEALTHCHECK_PORT: ${HEALTHCHECK_PORT}
      MISSION: ${MISSION}
      SPACECRAFT: ${SPACECRAFT}
      PROJECT_NAME: ${PROJECT_NAME}
    networks:
      nos3-m01-sc01-00:
      nos3-m01-core-00:

  nos3-torquer-sim:
    image: nos3-base-local:dev
    env_file:
      - ./.env
    attach: true
    depends_on:
      nos3-fortytwo:
        condition: service_healthy
      nos3-fsw:
        condition: service_healthy
    container_name: sc01-torquer-sim
    hostname: trq-sim
    working_dir: /home/nos3/builds/nos3/sims/build/bin
    command: "./nos3-single-simulator -f ./nos3-simulator.xml generic-torquer-sim"
    volumes:
      - ${PWD}/${NOS3_CFG_PATH}/cfg/build/sims/nos3-simulator.xml:/home/nos3/builds/nos3/sims/build/bin/nos3-simulator.xml
    environment:
      HEALTHCHECK_PORT: ${HEALTHCHECK_PORT}
      MISSION: ${MISSION}
      SPACECRAFT: ${SPACECRAFT}
      PROJECT_NAME: ${PROJECT_NAME}
    networks:
      nos3-m01-sc01-00:
      nos3-m01-core-00:

  nos3-time:
    image: nos3-base-local:dev
    env_file:
      - ./.env
    attach: true
    depends_on:
      nos3-nos-engine-server:
        condition: service_healthy
    container_name: nos-time-driver
    hostname: nos-time-driver
    working_dir: /home/nos3/builds/nos3/sims/build/bin
    command: "./nos3-single-simulator -f ./nos3-simulator.xml time"
    volumes:
      - ${PWD}/${NOS3_CFG_PATH}/cfg/build/sims/nos3-simulator.xml:/home/nos3/builds/nos3/sims/build/bin/nos3-simulator.xml
    tty: true
    stdin_open: true
    privileged: true
    environment:
      HEALTHCHECK_PORT: ${HEALTHCHECK_PORT}
      MISSION: ${MISSION}
      SPACECRAFT: ${SPACECRAFT}
      PROJECT_NAME: ${PROJECT_NAME}
    networks:
      nos3-m01-sc01-00:
        aliases:
          - sc01-nos-time-driver
      nos3-m01-core-00:

  nos3-openmct:
    env_file:
      - ./.env
    build:
      context: ./services/openmct
      dockerfile: Containerfile
      args:
        DEPLOYMENT_ENVIRO: ${DEPLOYMENT_ENVIRO}
        HTTPS_PROXY: ${HTTPS_PROXY}
        HTTP_PROXY: ${HTTP_PROXY}
        NO_PROXY: ${NO_PROXY}

        IMAGE_URI: ${OPENMCT_IMAGE_URI}
        NVM_VERSION: ${OPENMCT_NVM_VERSION}
        NODE_VERSION: ${OPENMCT_NODE_VERSION}

        GIT_URL: ${OPENMCT_GIT_URL}
        GIT_COMMIT: ${OPENMCT_GIT_COMMIT}

    attach: true
    container_name: ${COMPOSE_PROJECT_NAME}-openmct
    hostname: ${COMPOSE_PROJECT_NAME}-openmct
    working_dir: "/opt/openmct"
    volumes:
      - "${PWD}/services/openmct/entrypoint.sh:/opt/openmct/entrypoint.sh"
      - "${PWD}/services/openmct/webpack.dev.mjs:/opt/openmct/.webpack/webpack.dev.mjs"
      - "${PWD}/services/openmct/example/index.js:/opt/openmct/example/index.js"
      - "${PWD}/services/openmct/example/make-example-events.mjs:/opt/openmct/example/make-example-events.mjs"      
    command: '/opt/openmct/entrypoint.sh'
    healthcheck:
      test: ["CMD-SHELL", "curl http://localhost:9000/"]
      interval: 10s
      timeout: 5s
      retries: 30
      start_period: 30s
    depends_on:
      nos3-gsw:
        condition: service_healthy
    ports:
      - "127.0.0.1:9000:9000"
      - "127.0.0.1:8080:8080"
    environment:
      MISSION: ${MISSION}
      SPACECRAFT: ${SPACECRAFT}
      PROJECT_NAME: ${PROJECT_NAME}
    networks:
      nos3-m01-sc01-00:
        aliases:
          - openmct
          - sc01-openmct
      nos3-m01-core-00:

networks:
  nos3-m01-core-00:
    external: ${EXTERNAL_NETWORK_CORE:-false}
    name: nos3-m01-core
  nos3-m01-sc01-00:
    external: ${EXTERNAL_NETWORK_SC01:-false}
    name: nos3-m01-sc01
