version: "3"

dotenv:
  - ./.env

env:
  CONTAINER_BIN: docker
  CONTAINER_COMPOSE_BIN: " {{.CONTAINER_BIN}} compose "
  CONTAINER_DIR: ./docker
  COMPOSE_FILE: "{{.CONTAINER_DIR}}/compose.yaml"

  DEPLOYMENT_ENVIRO: '{{.DEPLOYMENT_ENVIRO | default ""}}'
  HTTP_PROXY: '{{.HTTP_PROXY | default ""}}'
  HTTPS_PROXY: '{{.HTTPS_PROXY | default ""}}'

  ENVIRO_SCRIPT: "./env.sh"
  ENVIRO_FILE: "./.env"

  MAVEN_HTTPS_PROXY: '-s./settings.xml'
  MINIMAL_PATH: ".."

tasks:
  default:
    desc: Shows this help message
    cmds:
      - task --list-all
    silent: true

  build-fortytwo:
    desc: Build fortytwo (42)
    deps:
      - env-create
      - set-permissions
    cmds:
      - |        
        source ${ENVIRO_FILE} && \
          ${CONTAINER_COMPOSE_BIN} -f ${COMPOSE_FILE} build --pull nos3-fortytwo

  build-yamcs:
    desc: Build yamcs
    deps:
      - env-create
      - set-permissions
    cmds:
      - |
        source ${ENVIRO_FILE} && \
          ${CONTAINER_COMPOSE_BIN} -f ${COMPOSE_FILE} build --pull nos3-gsw

  build-openmct:
    desc: Build openmct
    deps:
      - env-create
      - set-permissions
    cmds:
      - |
        source ${ENVIRO_FILE} && \
          ${CONTAINER_COMPOSE_BIN} -f ${COMPOSE_FILE} build --pull nos3-openmct

  build:
    desc: Build all containers
    deps:
      - env-create
      - set-permissions
    cmds:
      - |
        source ${ENVIRO_FILE} && \
          ${CONTAINER_COMPOSE_BIN} -f ${COMPOSE_FILE} build --pull nos3-fortytwo nos3-gsw nos3-openmct

  set-permissions:
    desc: set filesystem permissions, needed for restricted accounts
    cmds:
      - find . -name '*.sh'   -exec chmod 775 {} \; # Make sure all scripts are world executable
      - find . -name '*.py'   -exec chmod 775 {} \; # Make sure all scripts are world executable
      - find . -name '*.json' -exec chmod 664 {} \; # Make sure all .json files are world readable
      - find . -name '*.xml'  -exec chmod 664 {} \; # Make sure all .xml files are world readable
      - find ${HOME}/.nos3/   -name '*.xml' -exec chmod 666 {} \; # Make sure all .xml files are world readable

  up:
    desc: Bring up nos3 in detached state
    deps:
      - env-create
      - build
    cmds:
      - |
        source ${ENVIRO_FILE} && \
          ${CONTAINER_COMPOSE_BIN} --env-file ${ENVIRO_FILE} -f ${COMPOSE_FILE} up -d --remove-orphans
      - task info-services

  down:
    desc: Bring down nos3
    cmds:
      - |
        ${CONTAINER_COMPOSE_BIN} -f ${COMPOSE_FILE} down --remove-orphans || true

  up-minimum:
    desc: Bring up nos3 (minimum) in detached state
    deps:
      - down
      - env-create
      - build
    cmds:
      - |
        source ${ENVIRO_FILE} && \
        export MINIMAL_PATH="nos3" ; \
          ${CONTAINER_COMPOSE_BIN} \
            --env-file ${ENVIRO_FILE} \
            -f ${COMPOSE_FILE} up -d \
              nos3-fortytwo \
              nos3-nos-engine-server \
              nos3-fsw \
              nos3-gps-sim \
              nos3-time \
              nos3-radio-sim-cryptolib \
              nos3-truth42sim \
              nos3-gsw \
              nos3-openmct \
            --remove-orphans
      - task info-services

  sidecar:
    desc: Run sidecar to enable output
    cmds:
      - ./scripts/sidecar/sidecar.sh -c "/CFS/CMD/TO_ENABLE_OUTPUT"

  doitall:
    desc: Do it all for nos3
    cmds:
      - task down
      - sleep 5
      - task up
      - sleep 15
      - ${CONTAINER_BIN} ps -a | egrep -i 'exited|unhealthy|created|error' | grep -v STATUS || true
      - task sidecar
      - task info-services
    silent: true

  clean:
    desc: clean images, cache, volumes, and networks
    deps:
      - down
      - down-new
    cmds:
      - yes | ${CONTAINER_BIN} image prune --filter "dangling=true"
      - yes | ${CONTAINER_BIN} system prune -a
      - yes | ${CONTAINER_BIN} volume prune
      - yes | ${CONTAINER_BIN} network prune

  setup-maven:
    desc: Setup maven settings.xml with proxy info-services
    cmds:
      - echo "<settings><proxies></proxies></settings>" > ${CONTAINER_DIR}/yamcs/settings.xml

  purge-containers:
    desc: "WARNING: purge docker/podman images, cache, volumes, and networks"
    cmds:
      - task all-down || true
      - yes | ${CONTAINER_BIN} image prune --filter "dangling=true" || true
      - yes | ${CONTAINER_BIN} system prune -a || true
      - yes | ${CONTAINER_BIN} volume prune || true
      - yes | ${CONTAINER_BIN} network prune || true
      - echo

  info-services:
    desc: info on accessing various services
    cmds: 
      - echo; echo "How to access various services:"; echo
      - echo "open http://localhost:8090 to access yamcs/gsw"
      - echo "open http://localhost:30090/vnc.html to access fortytwo (42)"
      - echo "open http://localhost:9000 to access openmct"
      - echo
    silent: true

  env-create:
    desc: Create .env
    cmds:
      - |
        ${ENVIRO_SCRIPT} > ${ENVIRO_FILE}
