version: "3"

dotenv:
  - ./targets/docker/.env

env:
  TARGETS_DIR: ./targets
  SERVICES_DIR: ./services
  SCRIPTS_DIR: ./scripts

  PROJECT_NAME: '{{.PROJECT_NAME | default "nos3-m01-sc01"}}'
  COMPOSE_PROJECT_NAME: '{{.COMPOSE_PROJECT_NAME | default "nos3-m01-sc01"}}'

  CONTAINER_BIN: docker
  CONTAINER_COMPOSE_BIN: " {{.CONTAINER_BIN}} compose "

  CONTAINER_DIR: "{{.TARGETS_DIR}}/docker"
  COMPOSE_FILE: "{{.CONTAINER_DIR}}/compose.yaml"

  DEPLOYMENT_ENVIRO: '{{.DEPLOYMENT_ENVIRO | default ""}}'
  HTTP_PROXY: '{{.HTTP_PROXY | default ""}}'
  HTTPS_PROXY: '{{.HTTPS_PROXY | default ""}}'

  ENVIRO_SCRIPT: "{{.SCRIPTS_DIR}}/env.sh"
  ENVIRO_FILE: "{{.CONTAINER_DIR}}/.env"

  MAVEN_HTTPS_PROXY: '-s./settings.xml'
  MAVEN_SETTINGS_FILE: '{{.MAVEN_SETTINGS_FILE | default ""}}'

  NOS3_CFG_PATH: '{{.NOS3_CFG_PATH | default ".."}}'

tasks:
  default:
    desc: Shows this help message
    cmds:
      - task --list-all
    silent: true

  build-fortytwo:
    desc: Build fortytwo (42)
    deps:
      - env-create
      - set-permissions
    cmds:
      - |        
        source ${ENVIRO_FILE} && \
          ${CONTAINER_COMPOSE_BIN} -f ${COMPOSE_FILE} build --pull nos3-fortytwo

  build-yamcs:
    desc: Build yamcs
    deps:
      - env-create
      - setup-maven
      - set-permissions
    cmds:
      - |
        source ${ENVIRO_FILE} && \
          ${CONTAINER_COMPOSE_BIN} -f ${COMPOSE_FILE} build --pull nos3-gsw

  build-openmct:
    desc: Build openmct
    deps:
      - env-create
      - set-permissions
    cmds:
      - ${CONTAINER_BIN} pull docker.io/library/ubuntu:25.04 
      - |
        source ${ENVIRO_FILE} && \
          ${CONTAINER_COMPOSE_BIN} -f ${COMPOSE_FILE} build --pull nos3-openmct

  build-fsw:
    desc: Build nos3-base-local (fsw)
    deps:
      - env-create
      - set-permissions
    cmds:
      - |
        source ${ENVIRO_FILE} && \
          ${CONTAINER_COMPOSE_BIN} -f ${COMPOSE_FILE} build --pull nos3-fsw

  build:
    desc: Build all containers
    deps:
      - env-create
      - set-permissions
      - setup-maven
    cmds:
      - ${CONTAINER_BIN} pull docker.io/library/ubuntu:25.04 
      - |
        source ${ENVIRO_FILE} && \
          ${CONTAINER_COMPOSE_BIN} -f ${COMPOSE_FILE} build --pull nos3-fortytwo nos3-gsw nos3-openmct nos3-fsw

  set-permissions:
    desc: set filesystem permissions, needed for restricted accounts
    cmds:
      - find . -type f -name '*.sh'               -exec chmod 777 {} \; # Make sure all scripts are world executable
      - find . -type f -name '*.py'               -exec chmod 777 {} \; # Make sure all scripts are world executable
      - find . -type f -name '*.json'             -exec chmod 666 {} \; # Make sure all .json files are world readable
      - find . -type f -name '*.xml'              -exec chmod 666 {} \; # Make sure all .xml files are world readable
      - find . -type f -name '*.c'                -exec chmod 555 {} \; # Make sure all .xml files are world readable
      - find . -type f -name '*.h'                -exec chmod 555 {} \; # Make sure all .xml files are world readable
      - find ../cfg/build -type f -name '*.sh'    -exec chmod 777 {} \; # Make sure all scripts are world executable
      - find ../cfg/build -type f -name '*.py'    -exec chmod 777 {} \; # Make sure all scripts are world executable
      - find ../cfg/build -type f -name '*.json'  -exec chmod 666 {} \; # Make sure all .json files are world readable
      - find ../cfg/build -type f -name '*.xml'   -exec chmod 666 {} \; # Make sure all .xml files are world readable
      - find ${HOME}/.nos3/ -type f -name '*.xml' -exec chmod 666 {} \; # Make sure all .xml files are world readable

  up:
    desc: Bring up nos3 in detached state
    deps:
      - down
      - submodule-update
      - env-create
      - build
      - config-nos3-mission
      - config
      - set-permissions
    cmds:
      - |
        source ${ENVIRO_FILE} && \
          export NOS3_CFG_PATH=${NOS3_CFG_PATH}; \
          ${CONTAINER_COMPOSE_BIN} --env-file ${ENVIRO_FILE} -f ${COMPOSE_FILE} --project-name ${COMPOSE_PROJECT_NAME} up -d --force-recreate --remove-orphans
#      - task check-service-ready SERVICE_HOST=localhost SERVICE_PORT=8090
      - sleep 15
      - task sidecar
      - task info-services
      - task check-docker-ps
    silent: true

  down:
    desc: Bring down nos3
    cmds:
      - |
        ${CONTAINER_COMPOSE_BIN} -f ${COMPOSE_FILE} --project-name ${COMPOSE_PROJECT_NAME} down --remove-orphans || true

  up-minimum:
    desc: Bring up nos3 (minimum) in detached state
    deps:
      - down
      - env-create
      - build
      - config-nos3-mission
      - config
      - set-permissions
    cmds:
      - sleep 5
      - |
        source ${ENVIRO_FILE} && \
          export NOS3_CFG_PATH=${NOS3_CFG_PATH} ; \
            ${CONTAINER_COMPOSE_BIN} \
              --env-file ${ENVIRO_FILE} \
              -f ${COMPOSE_FILE} --project-name ${COMPOSE_PROJECT_NAME} up -d \
                nos3-fortytwo \
                nos3-nos-engine-server \
                nos3-fsw \
                nos3-gps-sim \
                nos3-time \
                nos3-radio-sim-cryptolib \
                nos3-truth42sim \
                nos3-gsw \
                nos3-openmct \
              --force-recreate \
              --remove-orphans
      - task check-service-ready SERVICE_HOST=localhost SERVICE_PORT=8090
      - task sidecar
      - task info-services
      - task check-docker-ps
    silent: true

  sidecar:
    desc: Run sidecar to enable output
    cmds:
      - ${SCRIPTS_DIR}/sidecar.sh -c "/CFS/CMD/TO_ENABLE_OUTPUT"
    silent: true

  clean:
    desc: clean nos3 configuration
    deps:
      - down
    cmds:
      - cd ../ && make clean

  clean-containers:
    desc: clean images, cache, volumes, and networks
    deps:
      - down
    cmds:
      - yes | ${CONTAINER_BIN} image prune --filter "dangling=true"
      - yes | ${CONTAINER_BIN} system prune -a
      - yes | ${CONTAINER_BIN} volume prune
      - yes | ${CONTAINER_BIN} network prune

  setup-maven:
    desc: Setup maven settings.xml with proxy info-services
    cmds:
      - echo "<settings><proxies></proxies></settings>" > ${SERVICES_DIR}/yamcs/settings.xml
      - |
        if [ "${DEPLOYMENT_ENVIRO}" == "vmmoc" ]; then
          cp -f ${MAVEN_SETTINGS_FILE} ${HOME}/.nos3/yamcs/ || true
          cp -f ${MAVEN_SETTINGS_FILE} ${SERVICES_DIR}/yamcs/ || true
        fi

  check-docker-ps:
    desc: check docker ps for any exited|unhealthy|created|error containers
    cmds:
      - |
        ${CONTAINER_BIN} ps -a | egrep -i 'exited|unhealthy|created|error' | grep -v STATUS || true
    silent: true
    
  check-service-ready:
    env:
      SERVICE_HOST: '{{.SERVICE_HOST | default "localhost"}}'
      SERVICE_PORT: '{{.SERVICE_PORT | default "8090"}}'
    desc: wait for a service to be ready on a given port
    cmds:
      - |
        echo "Waiting for service ${SERVICE_HOST}:${SERVICE_PORT} to be ready on port ${SERVICE_PORT}..."
        until nc -z ${SERVICE_HOST} ${SERVICE_PORT}; do
          sleep 1
        done
        echo "Service ${SERVICE_HOST}:${SERVICE_PORT} is ready on port ${SERVICE_PORT}!"
    silent: true

  purge-containers:
    desc: "WARNING: purge docker/podman images, cache, volumes, and networks"
    cmds:
      - task down || true
      - yes | ${CONTAINER_BIN} image prune --filter "dangling=true" || true
      - yes | ${CONTAINER_BIN} system prune -a || true
      - yes | ${CONTAINER_BIN} volume prune || true
      - yes | ${CONTAINER_BIN} network prune || true
      - echo

  info-services:
    desc: info on accessing various services
    cmds: 
      - task env-create
      - |
        source ${ENVIRO_FILE}
        echo; echo "How to access various services:"; echo; \
        echo "open http://localhost:8090 to access yamcs/gsw"; \
          echo "open http://localhost:30090/vnc.html to access fortytwo (42) and then click Connect"; \
        echo "open http://localhost:9000/#/browse/taxonomy:spacecraft/taxonomy:~SIM_42_TRUTH/taxonomy:~SIM_42_TRUTH~SIM_42_TRUTH_DATA/taxonomy:~SIM_42_TRUTH~SIM_42_TRUTH_DATA~BVB_2?tc.mode=fixed&tc.timeSystem=utc&tc.startBound=${SIM_T0_EPOCH_MILLISECONDS}&tc.endBound=${SIM_TF_EPOCH_MILLISECONDS}&view=plot-single"
        echo

    silent: true

  env-create:
    desc: Create .env file from env.sh script
    cmds:
      - |
        ${ENVIRO_SCRIPT} > ${ENVIRO_FILE}

  install-lazydocker:
    desc: Install lazydocker CLI tool (to view logs, etc)
    cmds:
      - |
        curl --silent https://raw.githubusercontent.com/jesseduffield/lazydocker/master/scripts/install_update_linux.sh | bash
      - |
        echo; echo "don't forget to add: ${HOME}/.local/bin:${PATH} to your ~/.bashrc or ~/.zshrc"; echo
      - |
        echo "watch a Lazydocker demo here: https://www.youtube.com/watch?v=NICqQPxwJWw"; echo
    silent: true

  config-nos3-mission:
    desc: configure nos3-mission.xml to set start-time
    deps:
      - env-create
    cmds:
      - |
        source ${ENVIRO_FILE} && \
          sed -Ei 's/(\s*)(\<start\-time\>).*(\<start\-time\>)/\1\2>'${START_TIME}'<\/\3/g' ../cfg/nos3-mission.xml && \
          sed -Ei 's/(\s*)(\<gsw\>).*(\<gsw\>)/\1\2>'${GSW_SOFTWARE}'<\/\3/g' ../cfg/nos3-mission.xml && \
          sed -Ei 's/(\s*)(\<fsw\>).*(\<fsw\>)/\1\2>'${FSW_SOFTWARE}'<\/\3/g' ../cfg/nos3-mission.xml

  config:
    desc: configure nos3 by running config.sh
    cmds:
      - cd ../ && ./scripts/cfg/config.sh

  submodule-update:
    desc: sync and update git submodules
    cmds:
      - git submodule sync; git submodule update --init --recursive; git submodule sync
    silent: false