#!/usr/bin/env bash

# A script to generate .env file for container deployments

# Simulation specific inputs
NOW=$(date -u +"%Y-%m-%d %H:%M:%S UTC")
SIM_T0_DATETIME="2026-01-01 00:00:00 UTC"
#SIM_T0_DATETIME="${NOW}"
J2000_REFERENCE_DATETIME="2000-01-01 12:00:00 UTC"
LEAP_SECONDS=37

GSW_SOFTWARE=yamcs
FSW_SOFTWARE=cfs

# Avoid updating the below variables unless you know what you are doing

# Time specific derivations
SIM_T0_EPOCH_SECONDS=$(date -ud "${SIM_T0_DATETIME}" +"%s")
J2000_EPOCH_SECONDS=$(date -ud "${J2000_REFERENCE_DATETIME}" +"%s")

cat << EOF
#
# Auto-generated by ${PWD}/$(basename $0) on $(date -u +"%Y-%m-%dT%H:%M:%S%z")
#

# Simulation specific configurations
SIM_T0_DATETIME="${SIM_T0_DATETIME}"
J2000_REFERENCE_DATETIME="${J2000_REFERENCE_DATETIME}"

# In epoch seconds
SIM_T0_EPOCH_SECONDS=${SIM_T0_EPOCH_SECONDS}
J2000_EPOCH_SECONDS=${J2000_EPOCH_SECONDS}

# In J2000 seconds
START_TIME=$((${SIM_T0_EPOCH_SECONDS}-${J2000_EPOCH_SECONDS}))

# Deployment specific configurations
DEPLOYMENT_ENVIRO=${DEPLOYMENT_ENVIRO}
HEALTHCHECK_PORT=${HEALTHCHECK_PORT}

# Proxy configurations, the proxy values come for the environment, 
# which is important for the vmmoc
HTTPS_PROXY=${HTTPS_PROXY}
HTTP_PROXY=${HTTP_PROXY}
NO_PROXY=${NO_PROXY}

# Maven/Java specific configurations
MAVEN_REPO_LOCAL=/home/nos3/.nos3/.m2/repository
MAVEN_HTTPS_PROXY="--settings ./settings.xml"
MAVEN_SETTINGS_FILE=${MAVEN_SETTINGS_FILE}

# 
NOS3_CFG_PATH=nos3

# 42 specific configurations
FORTYTWO_DISPLAY=:1
FORTYTWO_GIT_URL=https://github.com/nasa-itc/42.git
FORTYTWO_GIT_COMMIT=nos3-main
FORTYTWO_GIT_FOLDER=42
FORTYTWO_STARTUP_FOLDER=NOS3InOut
FORTYTWO_RECOMPILE=false
FORTYTWO_BASE_DIR=/opt/nasa-itc
FORTYTWO_VNC_PASSWORD=$(echo -n "foobar" | shasum -a 256 | cut -d" " -f1)

FORTYTWO_SIM_DATE="$(date -ud "@${SIM_T0_EPOCH_SECONDS}" +"%m %d %Y")"
FORTYTWO_SIM_TIME="$(date -ud "@${SIM_T0_EPOCH_SECONDS}" +"%H %M %S.%2N")"
FORTYTWO_LEAP_SECONDS=${LEAP_SECONDS}

# gsw+fsw specific configurations
GSW_SOFTWARE=${GSW_SOFTWARE}
FSW_SOFTWARE=${FSW_SOFTWARE}

COMPONENT_DIR=/home/nos3/builds/nos3/components

# yamcs specific configurations
YAMCS_DATA_DIR=/home/nos3/.nos3/yamcs/target/yamcs/yamcs-data
# YAMCS_ETC_DIR=/home/nos3/.nos3/yamcs/target/yamcs/yamcs-etc
# YAMCS_CACHE_DIR=/home/nos3/.nos3/yamcs/target/yamcs/yam
YAMCS_GIT_URL=https://github.com/nasa-itc/nos3_yamcs_master.git
YAMCS_GIT_COMMIT=nos3-dev

# openmct specific configurations
OPENMCT_IMAGE_URI=docker.io/library/ubuntu:25.04
OPENMCT_GIT_URL=https://github.com/akhenry/openmct-yamcs.git
OPENMCT_GIT_COMMIT=master
OPENMCT_NVM_VERSION=v0.40.1
OPENMCT_NODE_VERSION=v21.7.3

# nos3 specific configurations
NOS3_DIR=/home/nos3/.nos3
NOS3_USER=nos3
FLIGHT_SOFTWARE=cfs

# nasa-itc specific configurations
BASE_DIR=/opt/nasa-itc

EOF