#!/usr/bin/env bash

# A script to generate .env file for Docker deployments

cat << EOF
#
# Auto-generated by ${PWD}/$(basename $0) on $(date -u +"%Y-%m-%dT%H:%M:%S%z")
#

DEPLOYMENT_ENVIRO=${DEPLOYMENT_ENVIRO}
HEALTHCHECK_PORT=${HEALTHCHECK_PORT}

# Proxy configurations, the proxy values come for the environment, 
# which is important for the vmmoc
HTTPS_PROXY=${HTTPS_PROXY}
HTTP_PROXY=${HTTP_PROXY}
NO_PROXY=${NO_PROXY}

# Maven/Java specific configurations
MAVEN_REPO_LOCAL=/home/nos3/.nos3/.m2/repository
MAVEN_HTTPS_PROXY="--settings ./settings.xml"
MAVEN_SETTINGS_FILE=${MAVEN_SETTINGS_FILE}

# 
NOS3_CFG_PATH=..

# 42 specific configurations
FORTYTWO_DISPLAY=:1
FORTYTWO_GIT_URL=https://github.com/nasa-itc/42.git
FORTYTWO_GIT_COMMIT=nos3-main
FORTYTWO_GIT_FOLDER=42
FORTYTWO_STARTUP_FOLDER=NOS3InOut
FORTYTWO_RECOMPILE=false
FORTYTWO_BASE_DIR=/opt/nasa-itc
FORTYTWO_VNC_PASSWORD=$(echo -n "foobar" | shasum -a 256 | cut -d" " -f1)

# gsw specific configurations
GSW_SOFTWARE=yamcs
COMPONENT_DIR=/home/nos3/builds/nos3/components

# yamcs specific configurations
YAMCS_DATA_DIR=/home/nos3/.nos3/yamcs/target/yamcs/yamcs-data
# YAMCS_ETC_DIR=/home/nos3/.nos3/yamcs/target/yamcs/yamcs-etc
# YAMCS_CACHE_DIR=/home/nos3/.nos3/yamcs/target/yamcs/yam
YAMCS_GIT_URL=https://github.com/nasa-itc/nos3_yamcs_master.git
YAMCS_GIT_COMMIT=nos3-dev

# openmct specific configurations
OPENMCT_IMAGE_URI=docker.io/library/ubuntu:25.04
OPENMCT_GIT_URL=https://github.com/akhenry/openmct-yamcs.git
OPENMCT_GIT_COMMIT=master
OPENMCT_NVM_VERSION=v0.40.1
OPENMCT_NODE_VERSION=v21.7.3

# nos3 specific configurations
NOS3_DIR=/home/nos3/.nos3
NOS3_USER=nos3
FLIGHT_SOFTWARE=cfs

# nasa-itc specific configurations
BASE_DIR=/opt/nasa-itc

EOF