# -*- mode: ruby -*-
# vi: set ft=ruby :

#
# NASA Operational Simulator for Small Satellites (NOS3)
#

# Answer the following questions by commenting and uncommenting lines
# to select the desired mission configuration.

# 1) Virtual Machine Operating System
    #os = '1'  # CentOS
    os = '2'  # Ubuntu

# 2) Virtual Machine Memory
    vm_memory=4096
    #vm_memory=8192

# 3) Virtual Machine Cores
    vm_cores=2
    #vm_cores=4

# 4) Ground Station Software
    #gss = '0' # None
    #gss = '1' # AIT
    gss = '2' # COSMOS


###############################################################################
# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
###############################################################################

Vagrant.configure(2) do |config|  
  if os == '1' 
    config.vm.box = "bento/centos-7.6"
  end
  if os == '2'
    config.vm.box = "bento/ubuntu-18.04"
  end
  config.vm.box_version = "201812.27.0"
  config.vm.synced_folder "../", "/vagrant_parent"
  # X11 Forwarding
  config.ssh.forward_x11 = true

  # Save off ruby variable with VirtualBox version number
  vbox = VagrantPlugins::ProviderVirtualBox::Driver::Meta.new
  vbox_version = vbox.version

  config.vm.provider "virtualbox" do |vb|
    if os == '1' 
      vb.name = "NOS3_CentOS"
    end
    if os == '2' 
      vb.name = "NOS3_Ubuntu"
    end
    vb.gui = true
    vb.memory = vm_memory
    vb.cpus = vm_cores
    vb.customize ["showvminfo", :id]
    vb.customize ['storageattach', :id,  '--storagectl', 'IDE Controller', '--port', 1, '--device', 0, '--type', 'dvddrive', '--medium', 'emptydrive']
    vb.customize ["modifyvm", :id, "--vram", "128"]
    vb.customize ["modifyvm", :id, "--hwvirtex", "on"]
    vb.customize ["modifyvm", :id, "--ioapic", "on"]
    # Speed up ruby gem installs
    vb.customize ["modifyvm", :id, "--natdnsproxy1", "off"]
    vb.customize ["modifyvm", :id, "--natdnshostresolver1", "off"]
    # Connect network
    vb.customize ["modifyvm", :id, "--cableconnected1", "on"]
    # Clipboard
    if vbox_version.match(/^6.0/)
      vb.customize ["modifyvm", :id, '--clipboard', 'bidirectional']
    else
      # --clipboard changed to --clipboard-mode in VirtualBox 6.1.
      vb.customize ["modifyvm", :id, '--clipboard-mode', 'bidirectional']
    end
  end

  if os == '1'
    # CentOS
    installer_path = "installers/centos/nos3_centos_64_"
  else
    # Ubuntu
    installer_path = "installers/ubuntu/nos3_ubuntu_64_"
  end 

  config.vm.provision "shell", path: installer_path + "INIT.sh"
  config.vm.provision "shell", path: installer_path + "MIN.sh"

  if gss == '1'
    # AIT
    config.vm.provision "shell", path: installer_path + "AIT.sh"
  end
  if gss == '2'
    # COSMOS
    config.vm.provision "shell", path: installer_path + "COSMOS.sh"
  end 

  config.vm.provision "shell", path: installer_path + "CUSTOM.sh"

  config.vm.provision :reload
  config.vm.provision "shell", inline: <<-SHELL
    echo "--- "
    echo "--- VirtualBox Guest Additions ---"
    echo "--- "
    cd /tmp
    wget -q "http://download.virtualbox.org/virtualbox/#{vbox_version}/VBoxGuestAdditions_#{vbox_version}.iso"
    mount "/tmp/VBoxGuestAdditions_#{vbox_version}.iso" /media
    yes "y" | sh /media/VBoxLinuxAdditions.run
    umount /media
  SHELL
  config.vm.provision :reload

end
