apiVersion: v1
data:
  entrypoint.sh: "#!/bin/bash\n\nrm -f /tmp/.X1-lock || true\nrm -f /tmp/.X11-unix/X1
    || true\n\npkill -9 -f vncserver || true\npkill -9 -f Xvnc || true\npkill -9 -f
    websockify || true\n\n/opt/TurboVNC/bin/vncserver -securitytypes tlsnone,x509none,none
    && \\\n  sleep 5 && \\\n  websockify -D \\\n    --web=/usr/share/novnc/ \\\n    --cert=~/novnc.pem
    80 localhost:5901 \n    \nexport DISPLAY=${DISPLAY:-:1}\nexport DIR=/opt/nasa-itc\nexport
    GIT_FOLDER=${GIT_FOLDER}\n\nxterm &\n\nrm -rf /opt/nasa-itc/42/NO3InOut/{*.42,*.csv}
    \n\nif [ \"$RECOMPILE\" == \"true\" ]; then\n  cd /opt/nasa-itc/42 && \\\n    git
    fetch && \\\n    git checkout ${GIT_COMMIT} && \\\n    git pull origin && \\\n
    \   git submodule update && \\\n    make clean && \\\n    make -j2\nfi\n\nSTARTUP_FOLDER=${STARTUP_FOLDER:-NO3InOut}\n\ncd
    /opt/nasa-itc/42 && \\\n  xterm -e \"./42 ${STARTUP_FOLDER}\" &\n\necho \"Started
    42 with PID $!\"\n\ntail -f /dev/null\n"
kind: ConfigMap
metadata:
  name: nos3-m01-sc01-fortytwo-volumes
