apiVersion: v1
data:
  BASE_DIR: /opt/nasa-itc
  COMPONENT_DIR: /home/nos3/builds/nos3/components
  COMPOSE_PROJECT_NAME: nos3-m01-sc01
  DEPLOYMENT_ENVIRO: ""
  FORTYTWO_BASE_DIR: /opt/nasa-itc
  FORTYTWO_DISPLAY: :1
  FORTYTWO_GIT_COMMIT: nos3-main
  FORTYTWO_GIT_FOLDER: "42"
  FORTYTWO_GIT_URL: https://github.com/nasa-itc/42.git
  FORTYTWO_LEAP_SECONDS: "37"
  FORTYTWO_PORT: "30090"
  FORTYTWO_RECOMPILE: "false"
  FORTYTWO_SIM_DATE: '"01 06 2026"'
  FORTYTWO_SIM_TIME: '"18 46 59.00"'
  FORTYTWO_STARTUP_FOLDER: NOS3InOut
  FORTYTWO_VNC_PASSWORD: c3ab8ff13720e8ad9047dd39466b3c8974e592c2fa383d4a3960714caef0c4f2
  FSW_SOFTWARE: cfs
  GSW_SOFTWARE: yamcs
  HEALTHCHECK_PORT: ""
  HTTP_PROXY: ""
  HTTPS_PROXY: ""
  J2000_EPOCH_SECONDS: "946728000"
  J2000_REFERENCE_DATETIME: '"2000-01-01 12:00:00 UTC"'
  MAVEN_HTTPS_PROXY: '"--settings ./settings.xml"'
  MAVEN_REPO_LOCAL: /home/nos3/.nos3/.m2
  MAVEN_SETTINGS_FILE: ""
  MISSION: m01
  NO_PROXY: ""
  NOS3_BASE_DIR: /home/nos3/.nos3
  NOS3_CFG_PATH: ..
  NOS3_DIR: /home/nos3/.nos3
  NOS3_GIT_COMMIT: dev
  NOS3_GIT_URL: https://github.com/nasa/nos3
  NOS3_IMAGE_URI: docker.io/ivvitc/nos3-64:20251107
  NOS3_MISSION_CFG_FILE: ../cfg/nos3-mission.xml
  NOS3_USER: nos3
  OPENMCT_GIT_COMMIT: master
  OPENMCT_GIT_URL: https://github.com/akhenry/openmct-yamcs.git
  OPENMCT_IMAGE_URI: docker.io/library/ubuntu:25.04
  OPENMCT_NODE_VERSION: v21.7.3
  OPENMCT_NVM_VERSION: v0.40.1
  OPENMCT_PORT: "9000"
  PROJECT_NAME: nos3-m01-sc01
  SIM_T0_DATETIME: '"2026-01-06 18:46:29 UTC"'
  SIM_T0_EPOCH_MILLISECONDS: "1767725219000"
  SIM_T0_EPOCH_SECONDS: "1767725219"
  SIM_TF_EPOCH_MILLISECONDS: "1767728819000"
  SPACECRAFT: sc01
  START_TIME: "820997219"
  TIME_INTERVAL: "3600"
  TIME_INTERVAL_MILLISECONDS: "3600000"
  TIME_OFFSET_SECONDS: "+30"
  YAMCS_DATA_DIR: /home/nos3/.nos3/yamcs/target/yamcs/yamcs-data
  YAMCS_GIT_COMMIT: nos3-dev
  YAMCS_GIT_URL: https://github.com/nasa-itc/nos3_yamcs_master.git
  YAMCS_INSTANCES: nos3
  YAMCS_PORT: "8090"
kind: ConfigMap
metadata:
  name: nos3-m01-sc01-fortytwo
