---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
# Include ConfigMaps
  - ./configmap-args.yaml
  - ./configmap-env.yaml
  - ./configmap-volumes.yaml

  - ./deployment.yaml
  - ./service.yaml
  - ./ingress.yaml
