#!/bin/sh
# This hook is sourced after every virtualenv is activated.

if [ $VIRTUAL_ENV == "$HOME/.virtualenvs/ait" ]
then
    export AIT_ROOT="/home/nos3/AIT/AIT-Core"
    export AIT_CONFIG="/home/nos3/AIT/AIT-Core/config/config.yaml"
fi
	
if [ $VIRTUAL_ENV == "$HOME/.virtualenvs/ait-cfs" ]
then
    export AIT_ROOT="/home/nos3/AIT/AIT-Core"
    export AIT_CONFIG="/home/nos3/AIT/AIT-CFS/config/config.yaml"
fi