FROM ubuntu:25.04

#--- PROXY CONFIG (if needed)
ARG MAVEN_HTTPS_PROXY
ARG HTTPS_PROXY
ARG HTTP_PROXY
ARG NO_PROXY
ARG DEPLOYMENT_ENVIRO

ENV MAVEN_HTTPS_PROXY=${MAVEN_HTTPS_PROXY}
ENV HTTPS_PROXY=${HTTPS_PROXY}
ENV HTTP_PROXY=${HTTP_PROXY}
ENV NO_PROXY=${NO_PROXY}
ENV DEPLOYMENT_ENVIRO=${DEPLOYMENT_ENVIRO}

# Install dependencies
RUN apt-get update && \
    apt-get -y install \
        sudo git curl && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Set working directory
WORKDIR /opt

# Install nvm and node
ENV NVM_VERSION=v0.40.1
ENV NVM_URL=https://raw.githubusercontent.com/nvm-sh/nvm/${NVM_VERSION}/install.sh
ENV NVM_DIR=/opt/nvm
RUN mkdir -p $NVM_DIR

ENV NODE_VERSION=v21.7.3
ENV NODE_PATH=$NVM_DIR/versions/node/${NODE_VERSION}/bin
ENV PATH=${NVM_DIR}:${NODE_PATH}:${PATH}

# Install nvm and node
WORKDIR /opt
RUN curl -o- ${NVM_URL} | bash 
RUN . ${NVM_DIR}/nvm.sh && nvm install ${NODE_VERSION}

# Clone openmct-yamcs repo
ARG GIT_URL
ARG GIT_COMMIT

ENV GIT_URL=${GIT_URL}
ENV GIT_COMMIT=${GIT_COMMIT}

RUN git clone --recurse-submodules -b ${GIT_COMMIT} -j2 ${GIT_URL} openmct

# Set working directory to the cloned repo
WORKDIR /opt/openmct

# Install dependencies and build openmct-yamcs
RUN ${NODE_PATH}/npm install -loglevel verbose
RUN ${NODE_PATH}/npm run build:example:master -loglevel verbose

# Install dependencies
RUN apt-get update && \
    apt-get -y install \
        sudo iputils-ping vim netcat-traditional tmux tree && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

