CFS Health and Safety (HS) Application on  User's Guide: hs/fsw/src/hs_custom.c File Reference
hs_custom.c File Reference
#include "cfe.h"
#include "cfe_psp.h"
#include "osapi.h"
#include "hs_app.h"
#include "hs_cmds.h"
#include "hs_msg.h"
#include "hs_custom.h"
#include "hs_events.h"
#include "hs_monitors.h"
#include "hs_perfids.h"
Functions
void HS_IdleTask (void)
int32 HS_CustomInit (void)
void HS_CustomCleanup (void)
void HS_UtilizationIncrement (void)
void HS_UtilizationMark (void)
void HS_MarkIdleCallback (void)
void HS_CustomMonitorUtilization (void)
int32 HS_CustomCommands (CFE_SB_MsgPtr_t MessagePtr)
void HS_UtilDiagReport (void)
int32 HS_CustomGetUtil (void)
void HS_SetUtilParamsCmd (CFE_SB_MsgPtr_t MessagePtr)
void HS_SetUtilDiagCmd (CFE_SB_MsgPtr_t MessagePtr)
Function Documentation
void HS_CustomCleanup (void)
Definition at line 184 of file hs_custom.c.
References HS_MarkIdleCallback().
int32 HS_CustomCommands (CFE_SB_MsgPtr_t MessagePtr)
Definition at line 281 of file hs_custom.c.
References HS_SetUtilDiagCmd(), HS_SetUtilParamsCmd(), and HS_UtilDiagReport().
int32 HS_CustomGetUtil (void)
Definition at line 431 of file hs_custom.c.
References HS_UTIL_PER_INTERVAL_TOTAL.
int32 HS_CustomInit (void)
Definition at line 128 of file hs_custom.c.
References HS_IDLE_TASK_FLAGS, HS_IDLE_TASK_NAME, HS_IDLE_TASK_PRIORITY, HS_IDLE_TASK_STACK_PTR, HS_IDLE_TASK_STACK_SIZE, HS_IdleTask(), HS_MarkIdleCallback(), HS_UTIL_CONV_DIV, HS_UTIL_CONV_MULT1, HS_UTIL_CONV_MULT2, HS_UTIL_DIAG_MASK, and HS_UTIL_TIME_DIAG_ARRAY_MASK.
void HS_CustomMonitorUtilization (void)
Definition at line 261 of file hs_custom.c.
References HS_UTIL_CYCLES_PER_INTERVAL.
void HS_IdleTask (void)
Definition at line 83 of file hs_custom.c.
References HS_IDLETASK_PERF_ID, and HS_UtilizationIncrement().
Referenced by HS_CustomInit().
void HS_MarkIdleCallback (void)
Definition at line 243 of file hs_custom.c.
References HS_UtilizationMark().
Referenced by HS_CustomCleanup(), and HS_CustomInit().
void HS_SetUtilDiagCmd (CFE_SB_MsgPtr_t MessagePtr)
Definition at line 482 of file hs_custom.c.
Referenced by HS_CustomCommands().
void HS_SetUtilParamsCmd (CFE_SB_MsgPtr_t MessagePtr)
Definition at line 445 of file hs_custom.c.
Referenced by HS_CustomCommands().
void HS_UtilDiagReport (void)
Definition at line 317 of file hs_custom.c.
References HS_UTIL_TIME_DIAG_ARRAY_LENGTH.
Referenced by HS_CustomCommands().
void HS_UtilizationIncrement (void)
Definition at line 208 of file hs_custom.c.
Referenced by HS_IdleTask().
void HS_UtilizationMark (void)
Definition at line 221 of file hs_custom.c.
References HS_UTIL_CALLS_PER_MARK.
Referenced by HS_MarkIdleCallback().