/* Copyright (C) 2015 - 2015 National Aeronautics and Space Administration. All Foreign Rights are Reserved to the U.S. Government.

   This software is provided "as is" without any warranty of any, kind either express, implied, or statutory, including, but not
   limited to, any warranty that the software will conform to, specifications any implied warranties of merchantability, fitness
   for a particular purpose, and freedom from infringement, and any warranty that the documentation will conform to the program, or
   any warranty that the software will be error free.

   In no event shall NASA be liable for any damages, including, but not limited to direct, indirect, special or consequential damages,
   arising out of, resulting from, or in any way connected with the software or its documentation.  Whether or not based upon warranty,
   contract, tort or otherwise, and whether or not loss was sustained from, or arose out of the results of, or use of, the software,
   documentation or services provided hereunder

   ITC Team
   NASA IV&V
   ivv-itc@lists.nasa.gov
*/

#ifndef NOS3_GPSSIMDATAFILEPROVIDER_HPP
#define NOS3_GPSSIMDATAFILEPROVIDER_HPP

#include <vector>

#include <Client/Bus.hpp>

#include <sim_i_data_provider.hpp>
#include <gps_sim_data_point.hpp>

namespace Nos3
{
    /** \brief Class for a provider of GPS simulation data that provides data from a file that is generated by 42.
     *
     */
    class GPSSimDataFileProvider : public SimIDataProvider
    {
    public:
        /// @name Constructors / destructors
        //@{
        /// \brief Constructor taking a configuration object.
        /// @param  sc  The configuration for the simulation
        GPSSimDataFileProvider(const boost::property_tree::ptree& config);
        //@}

        /// @name Non-mutating public worker methods
        //@{
        /** \brief Method to retrieve GPS data.
         *
         * @returns                     A data point of GPS data.
         */
      virtual boost::shared_ptr<SimIDataPoint> get_data_point() const;
        //@}
    private:
        // Private helper methods
        boost::shared_ptr<GPSSimDataPoint> get_gps_data() const;
    	void get_gps_time(double absTime, int32_t& gps_week, int32_t& gps_seconds_in_week, double& gps_fractions_of_a_second) const;

        // Private data
        NosEngine::Transport::TransportHub      _hub;
        std::unique_ptr<NosEngine::Client::Bus> _time_bus;
        const double                            _absolute_start_time;
        const int64_t                           _sim_microseconds_per_tick;
        std::string _data_file;
        mutable int _file_loc;

    };
}

#endif
