name: nos3-m01-sc01

services:
  nos3-fortytwo:
    image: docker.io/haisamido/42:master
#    image: ghcr.io/ericstoneking/42:latest
#    image: ghcr.io/ericstoneking/42:latest@sha256:4570edd2ef615acfaceec61c3ce7498255fca9b7dd23632c62b0592519c2c7e0
#    image: ghcr.io/haisamido/nasa-itc-42:latest
#    image: ghcr.io/nasa-itc/42:master
    attach: true
    # deploy:
    #   resources:
    #     limits:
    #       cpus: '3'
    #       memory: "2048MB"
    #     reservations:
    #       cpus: '1'
    #       memory: "2048MB"
    container_name: sc_1_fortytwo
    hostname: fortytwo
    working_dir: "/opt/nasa-itc/"
    command: '/entrypoint.sh'
    volumes:
      - ${PWD}/../nos3/cfg/sims/InOut:/opt/nasa-itc/42/InOut
      # - ${HOME}/development/github.com/haisamido/nos3/deployments/docker/42/entrypoint.sh:/entrypoint.sh
      # - ${HOME}/development/github.com/haisamido/nos3/deployments/docker/42/startapp.sh:/startapp.sh
    ports:
      - "30090:80"
    environment:
      HEALTHCHECK_PORT: 60000
      DISPLAY: ":1"
    networks:
      - nos3_sc_1
      - nos3_core

  nos3-fsw:
    image: docker.io/haisamido/nos3-base:20250217
    attach: true
    # deploy:
    #   resources:
    #     limits:
    #       memory: "128M"
    #       cpus: ".100"
    #     reservations:
    #       memory: "128M"
    #       cpus: ".100"
    container_name: sc_1_nos_fsw
    hostname: nos_fsw
    working_dir: /builds/nos3/fsw/build/exe/cpu1
    command: "./core-cpu1 -R PO"
    sysctls:
      fs.mqueue.msg_max: 10000
    ulimits:
      rtprio: 99
    cap_add:
      - sys_nice
    environment:
      HEALTHCHECK_PORT: 60000
    networks:
      - nos3_sc_1
      - nos3_core

  nos3-nos_engine_server:
    image: docker.io/haisamido/nos3-base:20250217 
    attach: true
    # deploy:
    #   resources:
    #     limits:
    #       memory: "128M"
    #       cpus: ".100"
    #     reservations:
    #       memory: "128M"
    #       cpus: ".100"
    container_name: sc_1_nos_engine_server
    hostname: nos_engine_server
    working_dir: /builds/nos3/sims/build/bin
    command: "/usr/bin/nos_engine_server_standalone -f ./nos_engine_server_config.json"
    volumes:
      - ${PWD}/../nos3/cfg/sims/nos_engine_server_config.json:/builds/nos3/sims/build/bin/nos_engine_server_config.json
    tty: true
    environment:
      HEALTHCHECK_PORT: 60000
    networks:
      nos3_sc_1:
        aliases: 
          - nos-engine-server
          - sc_1_nos_engine_server
      nos3_core:

  nos3-gps:
    image: docker.io/haisamido/nos3-base:20250217 
    attach: true
    # deploy:
    #   resources:
    #     limits:
    #       memory: "128M"
    #       cpus: ".100"
    #     reservations:
    #       memory: "128M"
    #       cpus: ".100"
    container_name: sc_1_gps_sim
    hostname: sc_1_gps_sim
    working_dir: /builds/nos3/sims/build/bin
    command: "./nos3-single-simulator -f ./nos3-simulator.xml gps"
    volumes:
      - ${PWD}/../nos3/cfg/sims/nos3-simulator.xml:/builds/nos3/sims/build/bin/nos3-simulator.xml
    environment:
      HEALTHCHECK_PORT: 60000
    networks:
      - nos3_sc_1
      - nos3_core

  nos3-time:
    image: docker.io/haisamido/nos3-base:20250217 
    attach: true
    # deploy:
    #   resources:
    #     limits:
    #       memory: "128M"
    #       cpus: ".100"
    #     reservations:
    #       memory: "128M"
    #       cpus: ".100"
    container_name: nos_time_driver
    hostname: nos_time_driver
    working_dir: /builds/nos3/sims/build/bin
    command: "./nos3-single-simulator -f ./nos3-simulator.xml time"
    volumes:
      - ${PWD}/../nos3/cfg/sims/nos3-simulator.xml:/builds/nos3/sims/build/bin/nos3-simulator.xml
    tty: true
    stdin_open: true
    privileged: true
    environment:
      HEALTHCHECK_PORT: 60000
    networks:
      - nos3_sc_1
      - nos3_core

# TODO: issue is that ${HOME}/.nos3/yamcs is being mounted, and is always rebuilding, not functioning well
  nos3-gsw:
    image: docker.io/haisamido/yamcs-base:5.10.4
#    image: docker.io/haisamido/nos3-base:20250217
#    image: registry.appdat.jsc.nasa.gov/ssmo/images/ssmo/yamcs-base/yamcs:5.10.4
    attach: true
    # deploy:
    #   resources:
    #     limits:
    #       cpus: '3'
    #       memory: "2048MB"
    #     reservations:
    #       cpus: '1'
    #       memory: "2048MB"
    container_name: cosmos_openc3-operator_1
    hostname: cosmos
    working_dir: "${HOME}/.nos3/yamcs"
#    command: "mvn -Dmaven.repo.local=${HOME}/.nos3/.m2/repository -DCOMPONENT_DIR=${COMPONENT_DIR} yamcs:run"
    command: "mvn -DCOMPONENT_DIR=${COMPONENT_DIR} yamcs:run"
    volumes:
      - ${HOME}/.nos3/yamcs:${HOME}/.nos3/yamcs
      - ${HOME}/development/github.com/nasa/nos3/components/:/builds/nos3/components/
    ports:
      - "8090:8090"
      - "5012:5012"
    tty: true
    stdin_open: true
    privileged: true
    environment:
      COMPONENT_DIR: "/builds/nos3/components"
      HEALTHCHECK_PORT: 60000
    networks:
      nos3_sc_1:
        aliases: 
          - cosmos
      nos3_core:

  nos3-truth42sim:
    image: docker.io/haisamido/nos3-base:20250217
    attach: true
    # deploy:
    #   resources:
    #     limits:
    #       memory: "128M"
    #       cpus: ".100"
    #     reservations:
    #       memory: "128M"
    #       cpus: ".100"
    container_name: sc_1_truth42sim
    hostname: truth42sim
    working_dir: "/builds/nos3/sims/build/bin"
    command: "./nos3-single-simulator -f ./nos3-simulator.xml truth42sim"
    volumes:
      - ${PWD}/../nos3/cfg/sims/nos3-simulator.xml:/builds/nos3/sims/build/bin/nos3-simulator.xml
    tty: true
    stdin_open: true
    privileged: true
    environment:
      HEALTHCHECK_PORT: 60000
    networks:
      - nos3_sc_1
      - nos3_core

  nos3-nos_terminal:
    image: docker.io/haisamido/nos3-base:20250217
    attach: true
    # deploy:
    #   resources:
    #     limits:
    #       memory: "128M"
    #       cpus: ".100"
    #     reservations:
    #       memory: "128M"
    #       cpus: ".100"
    container_name: nos_terminal
    hostname: nos_terminal
    working_dir: "/builds/nos3/sims/build/bin"
    command: "./nos3-single-simulator -f ./nos3-simulator.xml  truth42sim"
    volumes:
      - ${PWD}/../nos3/cfg/sims/nos3-simulator.xml:/builds/nos3/sims/build/bin/nos3-simulator.xml
    tty: true
    stdin_open: true
    privileged: true
    environment:
      HEALTHCHECK_PORT: 60000
    networks:
      - nos3_sc_1
      - nos3_core

  nos3-nos_udp_terminal:
    image: docker.io/haisamido/nos3-base:20250217
    attach: true
    # deploy:
    #   resources:
    #     limits:
    #       memory: "128M"
    #       cpus: ".100"
    #     reservations:
    #       memory: "128M"
    #       cpus: ".100"
    container_name: nos_udp_terminal
    hostname: nos_udp_terminal
    working_dir: "/builds/nos3/sims/build/bin"
    command: "./nos3-single-simulator -f ./nos3-simulator.xml  truth42sim"
    volumes:
      - ${PWD}/../nos3/cfg/sims/nos3-simulator.xml:/builds/nos3/sims/build/bin/nos3-simulator.xml
    tty: true
    stdin_open: true
    privileged: true
    environment:
      HEALTHCHECK_PORT: 60000
    networks:
      - nos3_sc_1
      - nos3_core
  
networks:
  nos3_core:
    driver: bridge
  nos3_sc_1:
