---
apiVersion: apps/v1

kind: Deployment

metadata:
  name: nos3-m01-sc01-fortytwo
  labels:
    app: nos3-m01-sc01-fortytwo

spec:
  replicas: 1
  selector:
    matchLabels:
      app: nos3-m01-sc01-fortytwo
  template:
    metadata:
      labels:
        app: nos3-m01-sc01-fortytwo
    spec:
      containers:
        - args:
            - /entrypoint.sh
          env:
            - name: COMPONENT_NAME
              value: fortytwo
            - name: DISPLAY
              value: :1
          image: ghcr.io/haisamido/nos3-base-fortytwo:dev
          workingDir: /42
          imagePullPolicy: Always
          name: nos3-m01-sc01-fortytwo
          ports:
            - containerPort: 80
              protocol: TCP
          resources:
            limits:
              cpu: "3"
              memory: "2048Mi"
            requests:
              cpu: "1"
              memory: "2048Mi"
          securityContext:
            privileged: true
          volumeMounts:
            - mountPath: /entrypoint.sh
              name: nos3-m01-sc01-fortytwo-volumes
              subPath: entrypoint.sh
      hostname: fortytwo
      restartPolicy: Always
      volumes:
        - configMap:
            items:
              - key: entrypoint.sh
                path: entrypoint.sh
            name: nos3-m01-sc01-fortytwo-volumes
            defaultMode: 0555
          name: nos3-m01-sc01-fortytwo-volumes
