---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./configmaps/args-configmap.yaml
  - ./configmaps/env-configmap.yaml
  - ./configmaps/volumes-configmap.yaml
  - ./deployment.yaml
  - ./service.yaml
  - ./ingress.yaml
