apiVersion: v2
name: nos3
description: NOS3 Aerospace Simulation Platform - NASA Operational Simulator for Small Satellites
type: application
version: 0.1.0
appVersion: "dev"
keywords:
  - NASA
  - nos3
  - aerospace
  - simulation
  - satellite
  - yamcs
  - cfs
  - 42
maintainers:
  - name: haisamido
home: https://github.com/haisamido/nos3
sources:
  - https://github.com/nasa/nos3
