#!/usr/bin/env bash

# A script to generate .env file

cat << EOF
#
# Auto-generated by ${PWD}/$(basename $0) on $(date -u +"%Y-%m-%dT%H:%M:%S%z")
#

DEPLOYMENT_ENVIRO=${DEPLOYMENT_ENVIRO}

# Proxy configurations, the proxy values come for the environment, 
# which is important for the vmmoc
HTTPS_PROXY=${HTTPS_PROXY}
HTTP_PROXY=${HTTP_PROXY}
NO_PROXY=${NO_PROXY}

IMAGE_URI=docker.io/library/ubuntu:25.04
NVM_VERSION=v0.40.1
NODE_VERSION=v21.7.3

GIT_URL=https://github.com/akhenry/openmct-yamcs.git
GIT_COMMIT=master

EOF
