active: true
derived: false
header: ''
level: 1.0
links: []
normative: true
ref: ''
requirement-level: 2
reviewed: null
text: NOS shall be able to simulate different flight software (such as F' and cFS)
