active: true
derived: false
header: ''
level: 1.0
links: []
normative: true
ref: ''
requirement-level: 2
reviewed: null
text: |
  NOS shall have a simulation environment which is configurable:
  a. In its startup location
  b. In its startup time
  c. In configuration or state of the vehicle
