active: true
derived: false
header: ''
level: 1.0
links: []
normative: true
ref: ''
requirement-level: 2
reviewed: null
text: |
  NOS shall be able to be reconfigured to represent:
    - multiple disparate missions 
    - multiple scenarios within each mission
