active: true
derived: false
header: ''
level: 1.0
links: []
normative: true
ref: ''
requirement-level: 2
reviewed: null
text: NOS Shall be able to simulate different ground software (such as F', COSMOS, OpenC3, YAMCS)
