###############################################################################
# File: cFE Application Makefile 
#
#
# History:
#
###############################################################################
#
# Subsystem produced by this makefile.
#

##
## If this subsystem needs include files from another app, add the path here.
##
INCLUDE_PATH = \
-I..

all:
	gcc $(INCLUDE_PATH) -g -o cfe_fm_crc cfe_fm_crc.c

clean:
	rm cfe_fm_crc

