#!/usr/bin/env bash

# A script to generate .env file

cat << EOF
#
# Auto-generated by ${PWD}/$(basename $0) on $(date -u +"%Y-%m-%dT%H:%M:%S%z")
#

DEPLOYMENT_ENVIRO=${DEPLOYMENT_ENVIRO}

# Proxy configurations, the proxy values come for the environment, 
# which is important for the vmmoc
HTTPS_PROXY=${HTTPS_PROXY}
HTTP_PROXY=${HTTP_PROXY}
NO_PROXY=${NO_PROXY}
MAVEN_HTTPS_PROXY=${MAVEN_HTTPS_PROXY}

EOF
