#include "cfe.h"
#include "spacecop_stix_components.h"
#include "spacecop_mission_specific.h"
#include "spacecop_external_imports.h"
#include "cfe_tbl_filedef.h"

CommandMonitorEntryTable_t SPACECOP_CommandMonitorTable = {
	.CommandMonitorEntryCount=12,
	.CommandMonitorEntries={
		{
			.Command=1,
			.ActionOnMid={GENERIC_THRUSTER_CMD_MID},
			.ActionOnCommandCode=GENERIC_THRUSTER_ENABLE_CC,
			.HaveDeactivate=1,
			.DeactivateOnMid={GENERIC_THRUSTER_CMD_MID},
			.DeactivateOnCommandCode=GENERIC_THRUSTER_DISABLE_CC,
			.StixInfo={
					.Action=COUNT_DURATION,
					.StixId=propulsion_burn_duration_id
			},
			.enableML=0
		},
		{
			.Command=1,
			.ActionOnMid={CFE_TIME_CMD_MID},
			.ActionOnCommandCode=CFE_TIME_SET_TIME_CC,
			.HaveDeactivate=0,
			.StixInfo={
					.Action=COUNT_TOTAL,
					.StixId=adjust_time_id
			},
			.enableML=0
		},
		{
			.Command=0,
			.ActionOnMid={TO_LAB_HK_TLM_MID},
			.ActionOnCommandCode=0,
			.HaveDeactivate=0,
			.StixInfo={
					.Action=STORE_PACKET,
					.StixId=tlm_downlink_id
			},
			.enableML=0
		},
		{
			.Command=1,
			.ActionOnMid={CFE_ES_CMD_MID},
			.ActionOnCommandCode=CFE_ES_STOP_APP_CC,
			.HaveDeactivate=0,
			.StixInfo={
				.Action=ALERT_IMMEDIATELY,
				.StixId=state_change_id
			}
		},
		{
			.Command=1,
			.ActionOnMid={CFE_ES_CMD_MID},
			.ActionOnCommandCode=CFE_ES_START_APP_CC,
			.HaveDeactivate=0,
			.StixInfo={
				.Action=ALERT_IMMEDIATELY,
				.StixId=state_change_id
			}
		},
		{
			.Command=1,
			.ActionOnMid={CFE_ES_CMD_MID},
			.ActionOnCommandCode=CFE_ES_RESTART_APP_CC,
			.HaveDeactivate=0,
			.StixInfo={
				.Action=ALERT_IMMEDIATELY,
				.StixId=state_change_id
			}
		},
		{
			.Command=1,
			.ActionOnMid={CFE_ES_CMD_MID},
			.ActionOnCommandCode=CFE_ES_RELOAD_APP_CC,
			.HaveDeactivate=0,
			.StixInfo={
				.Action=ALERT_IMMEDIATELY,
				.StixId=state_change_id
			}
		},
		/*
		** Time manipulation. GNTM-7 (rule 14) counts adjust_time_id, but only
		** SET_TIME was feeding it. Every command below moves the clock and shares
		** that one counter, so the rule now also sees the quieter methods that
		** avoid a visible time jump.
		*/
		{
			.Command=1,
			.ActionOnMid={CFE_TIME_CMD_MID},
			.ActionOnCommandCode=CFE_TIME_SET_MET_CC,
			.HaveDeactivate=0,
			.StixInfo={
					.Action=COUNT_TOTAL,
					.StixId=adjust_time_id
			},
			.enableML=0
		},
		{
			.Command=1,
			.ActionOnMid={CFE_TIME_CMD_MID},
			.ActionOnCommandCode=CFE_TIME_SET_STCF_CC,
			.HaveDeactivate=0,
			.StixInfo={
					.Action=COUNT_TOTAL,
					.StixId=adjust_time_id
			},
			.enableML=0
		},
		{
			.Command=1,
			.ActionOnMid={CFE_TIME_CMD_MID},
			.ActionOnCommandCode=CFE_TIME_ADD_ADJUST_CC,
			.HaveDeactivate=0,
			.StixInfo={
					.Action=COUNT_TOTAL,
					.StixId=adjust_time_id
			},
			.enableML=0
		},
		{
			.Command=1,
			.ActionOnMid={CFE_TIME_CMD_MID},
			.ActionOnCommandCode=CFE_TIME_SUB_ADJUST_CC,
			.HaveDeactivate=0,
			.StixInfo={
					.Action=COUNT_TOTAL,
					.StixId=adjust_time_id
			},
			.enableML=0
		},
		{
			.Command=1,
			.ActionOnMid={CFE_TIME_CMD_MID},
			.ActionOnCommandCode=CFE_TIME_SET_LEAP_SECONDS_CC,
			.HaveDeactivate=0,
			.StixInfo={
					.Action=COUNT_TOTAL,
					.StixId=adjust_time_id
			},
			.enableML=0
		}
	}
};

// Table macro
CFE_TBL_FILEDEF(SPACECOP_CommandMonitorTable, SPACECOP.SC_CmdMonTbl, SP Cmd Mon Tbl, spacecop_cmdmon.tbl)
